### ISSUE TITLE
Compiler: string constants in case statements

### ISSUE THREAD

**Issue by Kamiryn123** [Leonard-The-Wise/NWScript-Npp#10]
As of .35 the NWN EE tooltset compiler supports string constants in case statements. 
See https://nwnlexicon.com/index.php?title=HashString for more information.
This new feature seems to be missing in 1.1.0.

**Comment by Leonard-The-Wise** [comment]
Thanks for reporting. I was talking with some Neverwinter developers a few days ago and it seems they intend to keep extending the language even further.

Unfortunately, the current state of NscLib of not being actively maintained anymore is making it more difficult for me to keep up with all the changes on new patches. 

I've been studying dropping NscLib entirely and adopting the new open source implementation of nwscript compiler (https://github.com/niv/neverwinter.nim/tree/master/neverwinter/nwscript), but it will take a while to rewrite the project for the new compiling API.

Meanwhile I suggest using the **if** statement instead of **switch**. I know, ugly workaround but still functional.

Cheers.

**Comment by Leonard-The-Wise** [comment]
Case solved with new compiler API from Neverwinter devs.
